apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: kagenti-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
        - name: mcp-inspector
          image: ghcr.io/modelcontextprotocol/inspector:0.16.8
          ports:
            - containerPort: 6274
            - containerPort: 6277
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
          - name: DANGEROUSLY_OMIT_AUTH
            value: "true"
          - name: ALLOWED_ORIGINS
            valueFrom:
              secretKeyRef:
                name: mcp-inspector-config
                key: ALLOWED_ORIGINS
          - name: MCP_PROXY_FULL_ADDRESS
            valueFrom:
              secretKeyRef:
                name: mcp-inspector-config
                key: MCP_PROXY_FULL_ADDRESS
          # - name: ALLOWED_ORIGINS
          #   value: http://mcp-inspector.localtest.me:8080
          # - name: MCP_PROXY_FULL_ADDRESS
          #   value: http://mcp-proxy.localtest.me:8080
          - name: HOST
            value: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
  namespace: kagenti-system
spec:
  selector:
    app: mcp-inspector
  ports:
  - name: ui
    port: 6274
    protocol: TCP
    targetPort: 6274
  - name: proxy
    port: 6277
    protocol: TCP
    targetPort: 6277
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-inspector
  namespace: kagenti-system
  labels:
    app: mcp-inspector
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "mcp-inspector.localtest.me"
  rules:
    - backendRefs:
        - name: mcp-inspector
          port: 6274 

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-proxy
  namespace: kagenti-system
  labels:
    app: mcp-inspector
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "mcp-proxy.localtest.me"
  rules:
    - backendRefs:
        - name: mcp-inspector
          port: 6277