{{- if .Values.components.istio.enabled }}
{{- if .Values.openshift }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/servicemeshoperator3.openshift-operators: ""
  name: servicemeshoperator3
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- else }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sailoperator 
  namespace: operators
spec:
  channel: stable
  name: sailoperator
  installPlanApproval: Automatic
  source: operatorhubio-catalog
  sourceNamespace: olm
{{- end }}
{{- end }}
