{{- if .Values.components.tekton.enabled }}
{{- if .Values.openshift }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: pipelines-1.14
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- else }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tektoncd-operator
  namespace: operators
spec:
  channel: alpha 
  name: tektoncd-operator
  installPlanApproval: Automatic
  source: operatorhubio-catalog
  sourceNamespace: olm
{{- end }}
{{- end }}
