apiVersion: v2
name: kagenti-deps
description: A Helm chart for deploying the kagenti dependencies
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: gateway-api
    # Version constraint changed from exact '1.3.0' to '~1.3.0' to allow patch updates (e.g., 1.3.1, 1.3.2).
    # Please ensure gateway-api maintains backward compatibility across patch versions, or review upgrade notes for details.
    version: "~1.3.0"
    repository: "file://../gateway-api"
    condition: components.gatewayApi.enabled
