# Global settings
openshift: true

# ------------------------------------------------------------------
#   Enable or disable components here
# ------------------------------------------------------------------
components:
  mcpInspector:
    enabled: true
  istio:
    enabled: true
  kiali:
    enabled: true  
  keycloak:
    enabled: true
  metricsServer:
    enabled: false
  otel:
    enabled: true
  registry:
    enabled: false
  spire:
    enabled: true
  tekton:
    enabled: true
  certManager:
    enabled: true  
  gatewayApi:  
    enabled: false
  ingressGateway:
    enabled: false 
  toolhive:
    enabled: true

common:
  kubectlImage: "quay.io/kubestellar/kubectl:1.30.14"

# ------------------------------------------------------------------
#  Components Configurations
# ------------------------------------------------------------------


# ------------------------------------------------------------------
#  Keycloak Configuration
# ------------------------------------------------------------------
keycloak:
  namespace: keycloak
  auth:
    adminUser: keycloakadmin
    adminPassword: your-secret-password
  httpRoute:
    annotations: {}
    parentRefs:
    - name: http
      sectionName: http
      namespace: kagenti-system
    hostnames:
      - "keycloak.localtest.me"
      - "www.keycloak.localtest.me"
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /headers


# ------------------------------------------------------------------
#  Istio Configuration
# ------------------------------------------------------------------
istio:
  communityCharts:
    enabled: false
  namespace: "istio-system"
  gatewayApiVersion: "v1.1.0"
  cni:
    profile: ambient
    namespace: istio-cni
  ztunnel:
    namespace: istio-ztunnel  
  base: {}
  istiod: 
    profile: ambient
    namespace: '{{ .Values.istio.namespace | quote }}'

httpGateway:
  name: http
  namespace: "kagenti-system"
# ------------------------------------------------------------------
#  Cert Manager Configuration
# ------------------------------------------------------------------
certManager:
  namespace: cert-manager-operator

# ------------------------------------------------------------------
#  Spire Configuration
# ------------------------------------------------------------------
spire:
  namespace: zero-trust-workload-identity-manager


registry:
  namespace: cr-system
  name: registry
  replicaCount: 1
  image:
    repository: ghcr.io/distribution/distribution
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  
  env:
    otelTracesExporter: "none"
    logLevel: "info"
