{{- if .Values.components.mcpGateway.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
  labels:
    {{- include "kagenti.labels" . | nindent 4 }}
    istio-discovery: enabled
    istio.io/dataplane-mode: ambient
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation  
{{- end }}  